"""Add user ad_detection_strategy and oneshot_model columns

Revision ID: 16724c87ef43
Revises: a1b2c3d4e5f6
Create Date: 2026-02-13 07:32:21.580865

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "16724c87ef43"
down_revision = "a1b2c3d4e5f6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "ad_detection_strategy",
                sa.String(length=20),
                nullable=False,
                server_default="llm",
            )
        )
        batch_op.add_column(
            sa.Column("oneshot_model", sa.String(length=100), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("oneshot_model")
        batch_op.drop_column("ad_detection_strategy")

    # ### end Alembic commands ###
