"""migration

Revision ID: 7033e6931510
Revises: a1b2c3d4e5f6
Create Date: 2026-02-22 21:16:17.360249

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7033e6931510"
down_revision = "a1b2c3d4e5f6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("llm_settings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "enable_llm_chapter_fallback_tagging",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("llm_settings", schema=None) as batch_op:
        batch_op.drop_column("enable_llm_chapter_fallback_tagging")

    # ### end Alembic commands ###
